# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: ^totalRP3/(Libs/(MSA-DropDownMenu-1\.0|TaintLess)/.*|Locales/.{4}\.lua)$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-yaml

  - repo: local
    hooks:
      - id: luacheck
        name: check lua
        entry: luacheck -q
        language: system
        types: [lua]
        require_serial: true

      - id: xmllint
        name: check xml
        entry: xmllint --noout --quiet --schema Scripts/UI.xsd
        language: system
        types: [xml]
        exclude: ^(Scripts/UI\.xsd|totalRP3/Bindings\.xml)$
        require_serial: true
