# Travis CI configuration file
# http://travis-ci.org

sudo: false
language: minimal

addons:
  apt:
    packages:
    - luarocks

git:
  depth: 150

install: luarocks install --local luacheck

script: /home/travis/.luarocks/bin/luacheck .

deploy:
  provider: script
  script: bash ./Scripts/release.sh
  on:
    tags: true

notifications:
  email:
    on_failure: always
    on_success: never

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
