# Travis CI configuration file
# http://travis-ci.org

dist: bionic
language: minimal

addons:
  apt:
    packages:
      - luarocks

install:
  - luarocks install --local luacheck
  - nvm install node
  - nvm install-latest-npm
  - npm install -g eclint

script:
  - /home/travis/.luarocks/bin/luacheck .
  - eclint check $(git ls-files '*.lua' '*.sh' '*.xml' ':!:totalRP3/libs/**/*' ':!:totalRP3/tools/Locale.lua')

deploy:
  provider: script
  script: bash ./Scripts/release.sh
  on:
    tags: true

notifications:
  email:
    on_failure: always
    on_success: never

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
