---
name: Import CurseForge Localization
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: -1

      - name: Generate Locales
        run: make locales
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Import CurseForge Localization
          branch: actions/import-cf-localization
          delete-branch: true
          title: Import CurseForge Localization
          body: Automated import of CurseForge localization.
          reviewers: Meorawr, Solanya
